### ISSUE TITLE
Latin America Dataset 

### ISSUE THREAD

**Issue by pablodz** [amo05/COVID-19_RD#1]
Hola, encontré tu repositorio y vamos a usar la data que subiste hasta hace 6 días, lo ideal sería contar con un archivo `.csv` que sea actualizado a diario para poder nosotros integrarlo de forma automática. Este tendría que tener el mismo formato que usa en el Excel
![image](https://user-images.githubusercontent.com/28235457/78512279-bf6b3600-7768-11ea-942f-b716b8fd77ef.png)
Gracias por su tiempo!
Le dejo el enlace a nuestro repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica

**Comment by EmmanuelCruz05** [comment]
Está bien, actualizare la data y la subiré en el formato que deseas

**Comment by pablodz** [comment]
Muchas gracias por colaborar, esto servirá para futuras investigaciones! Una pregunta, múltiples países de latinoamérica no están reportando cifras de recuperados. ¿Es el caso de su país? Estaré en contacto
